# .platform.app.yaml

# The name of this application, which must be unique within a project.
name: 'starterkit'

# The type key specifies the language and version for your application.
type: 'php:7.2'

# On PHP, there are multiple build flavors available. Pretty much everyone
# except Drupal 7 users will want the composer flavor.
build:
  flavor: 'none'

# The relationships of the application with services or other applications.
# The left-hand side is the name of the relationship as it will be exposed
# to the application in the PLATFORM_RELATIONSHIPS variable. The right-hand
# side is in the form `<service name>:<endpoint name>`.
relationships:
    redis: 'redis:redis'

# The configuration of the application when it is exposed to the web.
web:
    locations:
        '/':
            # The public directory of the application relative to its root.
            root: 'web'
            # The front-controller script which determines where to send
            # non-static requests.
            passthru: '/app.php'
            rules:
                # Provide a longer TTL (2 weeks) for aggregated assets files.
                '^/(bundles|fonts|images|js|scripts|style)':
                    expires: 2w
                '^/(?<filename>sitemap\.xml(-[0-9]+)?(\.gz)?)$':
                    passthru: '/sitemap/$filename'
        '/sitemap':
            root: 'var/sitemap'
            scripts: false
            allow: true
            expires: 300s
            passthru: '/app.php'
        # Allow uploaded files to be served, but do not run scripts.
        # Missing files get mapped to the front controller above.
        '/files':
            root: 'web/files'
            scripts: false
            allow: true
            passthru: '/app.php'

# The size of the persistent disk of the application (in MB).
disk: 2048

# The 'mounts' describe writable, persistent filesystem mounts in the application.
# The keys are directory paths relative to the application root. The values are
# strings such as 'shared:files/NAME' where NAME is just a unique name for the mount.
mounts:
    '/web/files': 'shared:files/web-files'
    '/var/cache': 'shared:files/cache'
    '/var/logs': 'shared:files/logs'
    '/var/sessions': 'shared:files/sessions'
    '/var/translations': 'shared:files/translations'
    '/var/filebeat': 'shared:files/filebeat'
    '/var/sitemap': 'shared:files/sitemap'

runtime:
    sizing_hints:
        request_memory: 15
    extensions:
        - newrelic

# The hooks that will be triggered when the package is deployed.
hooks:
    # Build hooks can modify the application files on disk but not access any services like databases.
    build: |
      set -eu
      IFS=$'\n\t'

      buildID=$(cat /proc/sys/kernel/random/uuid)
      echo "[`date --iso-8601=seconds`] build_start ${PLATFORM_PROJECT}.${PLATFORM_TREE_ID}.${buildID}"
      echo "${buildID}" > /app/app/buildID

      composer --no-ansi --no-interaction install --no-progress --prefer-dist --optimize-autoloader --no-dev

      # install and compile frontend assets
      bin/console --env=prod assets:install --no-debug
      bin/console --env=prod fos:js-routing:dump --no-debug
      npm install --quiet --no-progress --no-save
      /app/node_modules/.bin/gulp deploy
      rm -rf /app/node_modules

      # use our custom php.ini
      cp .platform.php.ini php.ini

      #   # download filebeat
      #   FILEBEAT_VERSION=6.3.1
      #   wget -q https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-${FILEBEAT_VERSION}-linux-x86_64.tar.gz
      #   tar xfz filebeat-${FILEBEAT_VERSION}-linux-x86_64.tar.gz
      #   cp filebeat-${FILEBEAT_VERSION}-linux-x86_64/filebeat bin/filebeat
      #   rm -rf filebeat-${FILEBEAT_VERSION}-linux-x86_64 filebeat-${FILEBEAT_VERSION}-linux-x86_64.tar.gz

      echo "[`date --iso-8601=seconds`] build_end ${PLATFORM_PROJECT}.${PLATFORM_TREE_ID}.${buildID}"
    # Deploy hooks can access services but the file system is now read-only.
    deploy: |
      set -eu
      IFS=$'\n\t'

      # Empty logs before writing anything in it
      echo -n > /var/log/access.log
      echo -n > /var/log/error.log
      echo -n > /var/log/deploy.log
      echo -n > /var/log/php.access.log

      deployID="$(cat /app/app/buildID).$(cat /proc/sys/kernel/random/uuid)"
      echo "[`date --iso-8601=seconds`] deploy_start ${PLATFORM_PROJECT}.${PLATFORM_TREE_ID}.${deployID}"

      # cache
      rm -rf var/cache/*
      bin/console --env=prod cache:warmup

      # push our local translations to the backend
      bin/console --env=prod wizaplace:translations:push

      bin/logrotate.sh

      DEPLOY_END=$(date +%s%N)
      echo "[`date --iso-8601=seconds`] deploy_end ${PLATFORM_PROJECT}.${PLATFORM_TREE_ID}.${deployID}"

crons:
    translations:
        # regularly pull translations' values from the backend
        spec: '*/5 * * * *'
        cmd: 'php bin/console --env=prod wizaplace:translations:pull && bin/console --env=prod cache:warmup'
    # filebeat:
    #     spec: '*/5 * * * *'
    #     cmd: './bin/filebeat.sh'
    sitemap:
        spec: '*/30 * * * *'
        cmd: 'php bin/console --env=prod sitemap:generate'
    daily_logrotate:
        spec: '0 4 * * *'
        cmd: 'bin/logrotate.sh'
    snapshot:
        # Take a snapshot automatically every night at 3 am (UTC).
        spec: '0 3 * * *'
        cmd: |
            if [ "$PLATFORM_BRANCH" = master ]; then
                platform snapshot:create --yes --no-wait
            fi
    renewcert:
        # Force a redeploy at 9 am (UTC) on the 14th of every month.
        spec: '0 9 14 * *'
        cmd: |
            if [ "$PLATFORM_BRANCH" = master ]; then
                platform redeploy --yes --no-wait
            fi
