path.data: /app/var/filebeat/data
path.logs: /app/var/filebeat/logs

filebeat.prospectors:
- input_type: log
  paths:
    - /var/log/access.log
  fields:
    document_type: apache_access
  tags: ["front"]

- input_type: log
  paths:
    - /var/log/error.log
  fields:
    document_type: apache_error
  tags: ["front"]

- input_type: log
  paths:
    - /app/var/logs/prod.json
  tags: ["front"]
  json.keys_under_root: true
  fields:
    document_type: app

- input_type: log
  paths:
    - /var/log/deploy.log
  fields:
    document_type: deploy
  tags: ["front"]

- input_type: log
  paths:
    - /var/log/php.access.log
  fields:
    document_type: php_access
  tags: ["front"]

output.logstash:
  hosts: ["logs.wizacha.com:5044"]
