path.home: /app/var/filebeat

logging.level: warning
logging.to_files: true
logging.to_syslog: false
logging.files:
  name: filebeat.log

filebeat.config:
  modules:
    enabled: false

filebeat.inputs:
- type: log
  paths:
    - /var/log/access.log
  fields:
    document_type: apache_access
  tags: ["front", "${PROJECT_NAME}"]

- type: log
  paths:
    - /var/log/error.log
  fields:
    document_type: apache_error
  tags: ["front", "${PROJECT_NAME}"]

- type: log
  paths:
    - /app/var/logs/prod.json
  tags: ["front", "${PROJECT_NAME}"]
  json.keys_under_root: true
  fields:
    document_type: app

- type: log
  paths:
    - /var/log/deploy.log
  fields:
    document_type: deploy
  tags: ["front", "${PROJECT_NAME}"]
  close_eof: true
  clean_inactive: 1m

- type: log
  paths:
    - /var/log/php.access.log
  fields:
    document_type: php_access
  tags: ["front", "${PROJECT_NAME}"]

output.logstash:
  hosts: ["logs.wizacha.com:5044"]
