parameters:
    googlemaps.api_key: '%env(GOOGLE_MAP_API_KEY)%'
    wizaplace.system_user_password: '%env(WIZAPLACE_SYSTEM_USER_PASSWORD)%'
    api.connect_timeout: '%env(API_CONNECT_TIMEOUT)%'
    api.read_timeout: '%env(API_READ_TIMEOUT)%'
    api.timeout: '%env(API_TIMEOUT)%'
    secret: '%env(APP_SECRET)%'
    http_host: '%env(HTTP_HOST)%'
    version: '%env(APP_VERSION)%'
    # default env values
    env(API_BASE_URL): 'https://sandbox.wizaplace.com/api/v1/'
    env(API_CONNECT_TIMEOUT): 30
    env(API_READ_TIMEOUT): 30
    env(API_TIMEOUT): 30
    env(SENTRY_DSN): ~
    env(WIZAPLACE_SYSTEM_USER_PASSWORD): ""
    env(APP_VERSION): ~
    env(APP_SECRET): ~
    env(HTTP_HOST): localhost
    env(GOOGLE_MAP_API_KEY): 'AIzaSyAw9jadoH_dgVqvbLU5tjAlsEZ75qt1TTw' #@TODO: override me
