# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory: ~
        wizaplace:
            id: AppBundle\Security\UserProvider

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            simple_preauth:
                authenticator: AppBundle\Security\SessionAuthenticator
            simple_form:
                authenticator: AppBundle\Security\FormAuthenticator
                check_path: login
                login_path: home
                username_parameter: 'email'
                password_parameter: 'password'
            logout:
                path: logout
                target: home
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
    access_control:
        - { path: ^/profil, roles: [ ROLE_USER ] }
