version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.1-cli-node-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - run: sudo composer self-update
      - restore_cache:
          keys:
            - composer-{{ checksum "composer.lock" }}
            # fallback to using the latest cache if no exact match is found
            - composer-
      - run: make composer-install-ci
      - save_cache:
          paths:
            - ./vendor
          key: composer-{{ checksum "composer.lock" }}
      - restore_cache:
          keys:
            - node-{{ checksum "package-lock.json" }}
            # fallback to using the latest cache if no exact match is found
            - node-
      - run: make npm-install
      - save_cache:
          paths:
            - ./node_modules
          key: node-{{ checksum "package-lock.json " }}

  css:
    docker:
      - image: circleci/php:7.1-cli-node-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-{{ checksum "package-lock.json" }}
            # fallback to using the latest cache if no exact match is found
            - node-
      - run: make lint-css assets

  lint:
    docker:
      -image: circleci/php:7.1-cli-node-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - composer-{{ checksum "composer.lock" }}
            # fallback to using the latest cache if no exact match is found
            - composer-
      - run: make lint-php
      - run: make stan
      - run: make lint-twig
      - run: make lint-yaml
      - run: make lint-xliff
      - run: make lint-json

workflows:
  version: 2
  build:
    jobs:
      - build
  assets:
    jobs:
      - css
  lint:
    jobs:
      - lint
